config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  get '/sign_up' => 'users#new'
  resources :users

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  get '/logout' => 'sessions#destroy'

  resources :user, only: [:show] do
    resources :weights, only: [:new, :create]
  end

  get '/register-a-team' => 'home#new_team'
  post '/register-a-team/complete' => 'home#team_registered'
  get '/register-a-team/complete' => 'home#team_registered'

end

app/models/team.rb
class Team < ActiveRecord::Base
  has_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :weights
  belongs_to :team
  
  validates :username, presence: true
  validates :email, presence: true, uniqueness: true

  has_secure_password

  def self.log_in(email, password)
    user = User.find_by(email: email.downcase)
    user && user.authenticate(password)
  end


  def current_user?(current_user)
    return false if current_user == nil
    current_user.id == self.id ? true : false
  end

  def profile_pic
    picture = self.photo_url
    if picture == nil || picture == ""
      "http://images.cdn4.stockunlimited.net/clipart/add-user-icon_1598354.jpg"
    else
      picture
    end
  end

  def ranking

  end

end

app/models/weight.rb
class Weight < ActiveRecord::Base
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :require_login

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def require_login
    if current_user.nil?
      flash[:error] = "You must be logged in to view this section"
      redirect_to login_path
    end
  end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :require_login, only: [:index, :new_team, :team_registered]


  def index
    @users = User.all
  end

  def new_team
    @team = Team.new
  end

  def team_registered
    @code = SecureRandom.hex(3)
    @email = team_create_params
    TeamCodeMailer.team_code(@email, @code).deliver
  end

  def team_create_params
  params.permit(:email)
end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
  end

  def create
    @user = User.log_in(params[:session][:email], params[:session][:password])
    if @user
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    session.delete :user_id
    redirect_to root_path
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_action :require_login, only: [:new, :create]
  before_action :correct_user,   only: [:index, :update, :show, :edit, :update]


  def new
    @user = User.new
  end

  def create
    @user = User.new(user_create_params[:user])
    if @user.save
      redirect_to user_path(@user)
    else
      render '/sign_up'
    end
  end

  def index
    @user = User.all
  end

  def update
    user = User.find(params[:id])
    user.update(user_create_params[:user])
    redirect_to user_path(user)
  end

  def edit
    @user = User.find(params[:id])
    render :new
  end

  def show
    @user = User.find(params[:id])
  end

  def correct_user
    @user = User.find(current_user.id)
    redirect_to(root_path) unless @user == current_user
  end

  private

  def user_create_params
    params.permit(user: [:first_name, :username, :email, :password, :password_confirmation,:photo_url, :account_manager])
  end
end

app/controllers/weights_controller.rb
class WeightsController < ApplicationController
  def new
    @weight = Weight.new
    @user = User.find(params[:user_id])
  end

  def create
    @weight = Weight.new(create_weight_params[:weight])
    if @weight.save
      redirect_to user_path(params[:user_id])
    else
      render :new
    end
  end

  private
  def create_weight_params
    params.permit(weight: [:weight, :record_date, :user_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_page
    request.env['PATH_INFO']
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/weights_helper.rb
module WeightsHelper
end

app/views/home/index.html.erb
<div class="home-pg">
  <img src="/assets/group working out with logo" width="80%" >
  <% if !current_user %>
    <div class="center">
      <%= link_to(image_tag("/assets/register a team sign", :alt =>  "alt text", :class =>"btn"), "/register-a-team")%>
    </div>

  <% end %>
</div>

app/views/home/new_team.html.erb
  <div class="register">
    <img src="/assets/regester-a-team" width="40%" >
  </div>

  <div class="reg-pg">
    <img src="/assets/drake" width="80%" >
    <div class="reg-center-bg">
      <div class="reg-center">
        <%= form_tag("/register-a-team/complete", :method => :post, class: "form-inline") do %>
          <div class="field">
            <%= label_tag "Account Manager Email Address" %><br>
            <%= text_field_tag :email %>
          </div>
          <div class="field">
            <%= label_tag "Team Name" %><br>
            <%= text_field_tag :email %>
          </div>

          <div class="field">
            <%= label_tag "Start Date" %><br>
            <%= text_field_tag :start_date %>
          </div>
          <div class="field">
            <%= label_tag "End Date" %><br>
            <%= text_field_tag :end_date %>
          </div>

          <div class="field">
            <%= label_tag "Weigh-in Date" %><br>
            <%= text_field_tag :weigh_in_date %>
          </div>

          <div class="actions"><br>
            <%= submit_tag "Submit", class: "btn btn-primary"  %>
          </div>

        <%end%>
      </div>

    </div>
  </div>

app/views/home/team_registered.html.erb
  <div class="register">
  </div>

  <div class="reg-complete-pg">
    <img src="/assets/boxing" style="width: 50%;">
    <div class="reg-center-bg">
      <div class="reg-complete-center">

        <p class="lead">YOUR GROUP CODE IS: <%= @code %></p>
      </div>

    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Summer16</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="build.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>
<!-- HEADER *******************************************************-->
  <!-- <div class="header"> -->
    <div class="thumbnail" style="  padding-bottom: 0px; margin-bottom: 0px;">
      <img class="portrait" src="/assets/beach chairs2.jpg" alt="Beach chairs2" style=" width: 100%; height: 443px;">
    	<!-- <img src="beach chairs" class="img-responsive"> -->
       </div>
    <!-- </div> -->
  <!-- NAV BAR ******************************************************-->
  <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <div class="navbar-brand">Summer16!</div>
        </div>
        <ul class="nav navbar-nav">
          <li class="<%= "active" if current_page == '/' %>"><%= link_to "HOME", root_path %></li>
        </ul>

        <% if current_user %>
          <ul class="nav navbar-nav navbar-right">
            <li class="<%= "active" if current_page == "/users/#{current_user.id}" %>"><%= link_to user_path(current_user.id) do %><span class="glyphicon glyphicon-user"></span> User Profile<% end %></li>
            <li><%= link_to logout_path, method: "delete" do %><span class="glyphicon glyphicon-log-out"></span> Log Out<% end %></li>
          </ul>
        <% else %>
          <ul class="nav navbar-nav navbar-right">
            <li class="<%= "active" if current_page == '/users/new' %>"><%= link_to new_user_path do %><span class="glyphicon glyphicon-user"></span> Sign Up<% end %></li>
            <li class="<%= "active" if current_page == '/login' %>"><%= link_to login_path do %><span class="glyphicon glyphicon-log-in"></span> Log In<% end %></li>
          </ul>
        <% end %>
      </div>
    </nav> <!-- END NAV BAR -->

</div> <!-- END HEADER -->


<!-- YIELD ******************************************************-->
    <!-- <article class = "container"> -->
      <%= yield %>
    <!-- </article> -->
</body>
</html>

app/views/users/index.html.erb
       <% date = ["May-12", "May-19", "May-26",  "June-02", "June-09"] %>
       <div class="profile-content">
         <h3>Weign-in Summary</h2>
         <table class="table table-striped">
           <thead>

             <tr class = "header">
               <th colsapn=2>Ranking </th>

               <th class = "header">User</th>
               <% date.each do |date| %>
               <th class = "header">
                 <%= date %>
               </th>
               <% end %>
               <th> TOTAL </th>

             </tr>
           </thead>
           <% count = 1 %>
           <tbody class="table-body">
             <% @user.sort{|user| user.weights.last && user.weights.first ? (user.weights.last.weight - user.weights.first.weight) : -1 }.each do |user| %>
             <tr>
              <td class="ranking"> <%= count %> </td>
               <td class="profile-table-pic">
        					<div class="profile-userpic-all">
        							<img src="<%= user.profile_pic %>" class="media-photo">
        						</a>
        						<div class="media-body">
        							<span class="title"><%= user.username%></span>
        						</div>
        					</div>
        				</td>
                 <td> - </td>
                 <td> <%= user.weights[1] ? number_to_percentage((((user.weights[1].weight - user.weights[0].weight)/user.weights[0].weight) * 100), precision: 2) : ""  %></td>
                 <td> <%= user.weights[2] ? number_to_percentage((((user.weights[2].weight - user.weights[0].weight)/user.weights[0].weight) * 100), precision: 2) : ""  %></td>
                 <td> <%= user.weights[3] ? number_to_percentage((((user.weights[3].weight - user.weights[0].weight)/user.weights[0].weight) * 100), precision: 2) : ""  %></td>
                 <td> <%= user.weights[4] ? number_to_percentage((((user.weights[4].weight - user.weights[0].weight)/user.weights[0].weight) * 100), precision: 2) : ""  %></td>
                 <td> <%= user.weights.first && user.weights.last ? number_to_percentage((((user.weights.last.weight - user.weights.first.weight)/user.weights.first.weight) * 100), precision: 2) : ""  %></td>
                 <% count += 1 %>
             </tr>
             <% end %>

           </tbody>
         </table>
       </div>

 		</div>
 	</div>
 </div>

app/views/users/index1.html.erb
 <!-- The classes that can be used are: .active, .success, .info, .warning, and .danger           -->
 <div class="container">
   <table class="table table-striped", class="table table-hover">
     <thead>
       <tr>
         <th class="headings" colspan=9>A-TEAM SUMMARY </tr>
       </tr>
       <tr class="headings">
         <th></th>
         <th></th>
         <th>A-TEAM</th>
         <th>Weight for Date</th>
       </tr>
     </thead>
     <tbody>
       <% @user.each do |user| %>
        <tr class="row">
          <td class = "table-userpic">
            <div class = "userpic">
              <img src=<%= user.profile_pic %> class="img-responsive" alt="">
            </div>
          </td>
          <td><%= user.username %></td>
          <td>weight %</td>
        <% end %>
      </tr>
     </tbody>
   </table>
 </div>



 <div class="table-container">
 	<table class="table table-filter">
 		<tbody>
      <% @user.each do |user| %>
 			<tr data-status="pagado">
 				<!-- <td>
 					<div class="ckbox">
 						<input type="checkbox" id="checkbox1">
 						<label for="checkbox1"></label>
 					</div>
 				</td> -->
 				<!-- <td>
 					<a href="javascript:;" class="star">
 						<i class="glyphicon glyphicon-star"></i>
 					</a>
 				</td> -->
 				<td>
 					<div class="media">
 						<a href="#" class="pull-left">
 							<img src="<%= user.profile_pic %>" class="media-photo">
 						</a>
 						<div class="media-body">
 							<span class="media-meta pull-right">user.username</span>
 							<h4 class="title">
 								Lorem Impsum
 								<span class="pull-right pagado">(Pagado)</span>
 							</h4>
 							<p class="summary">Ut enim ad minim veniam, quis nostrud exercitation...</p>
 						</div>
 					</div>
 				</td>
 			</tr>
      <% end %>

 			<tr data-status="pendiente">
 				<td>
 					<div class="ckbox">
 						<input type="checkbox" id="checkbox3">
 						<label for="checkbox3"></label>
 					</div>
 				</td>
 				<td>
 					<a href="javascript:;" class="star">
 						<i class="glyphicon glyphicon-star"></i>
 					</a>
 				</td>
 				<td>
 					<div class="media">
 						<a href="#" class="pull-left">
 							<img src="https://s3.amazonaws.com/uifaces/faces/twitter/fffabs/128.jpg" class="media-photo">
 						</a>
 						<div class="media-body">
 							<span class="media-meta pull-right">Febrero 13, 2016</span>
 							<h4 class="title">
 								Lorem Impsum
 								<span class="pull-right pendiente">(Pendiente)</span>
 							</h4>
 							<p class="summary">Ut enim ad minim veniam, quis nostrud exercitation...</p>
 						</div>
 					</div>
 				</td>
 			</tr>
 			<tr data-status="cancelado">
 				<td>
 					<div class="ckbox">
 						<input type="checkbox" id="checkbox2">
 						<label for="checkbox2"></label>
 					</div>
 				</td>
 				<td>
 					<a href="javascript:;" class="star">
 						<i class="glyphicon glyphicon-star"></i>
 					</a>
 				</td>
 				<td>
 					<div class="media">
 						<a href="#" class="pull-left">
 							<img src="https://s3.amazonaws.com/uifaces/faces/twitter/fffabs/128.jpg" class="media-photo">
 						</a>
 						<div class="media-body">
 							<span class="media-meta pull-right">Febrero 13, 2016</span>
 							<h4 class="title">
 								Lorem Impsum
 								<span class="pull-right cancelado">(Cancelado)</span>
 							</h4>
 							<p class="summary">Ut enim ad minim veniam, quis nostrud exercitation...</p>
 						</div>
 					</div>
 				</td>
 			</tr>
 			<tr data-status="pagado" class="selected">
 				<td>
 					<div class="ckbox">
 						<input type="checkbox" id="checkbox4" checked>
 						<label for="checkbox4"></label>
 					</div>
 				</td>
 				<td>
 					<a href="javascript:;" class="star star-checked">
 						<i class="glyphicon glyphicon-star"></i>
 					</a>
 				</td>
 				<td>
 					<div class="media">
 						<a href="#" class="pull-left">
 							<img src="https://s3.amazonaws.com/uifaces/faces/twitter/fffabs/128.jpg" class="media-photo">
 						</a>
 						<div class="media-body">
 							<span class="media-meta pull-right">Febrero 13, 2016</span>
 							<h4 class="title">
 								Lorem Impsum
 								<span class="pull-right pagado">(Pagado)</span>
 							</h4>
 							<p class="summary">Ut enim ad minim veniam, quis nostrud exercitation...</p>
 						</div>
 					</div>
 				</td>
 			</tr>
 			<tr data-status="pendiente">
 				<td>
 					<div class="ckbox">
 						<input type="checkbox" id="checkbox5">
 						<label for="checkbox5"></label>
 					</div>
 				</td>
 				<td>
 					<a href="javascript:;" class="star">
 						<i class="glyphicon glyphicon-star"></i>
 					</a>
 				</td>
 				<td>
 					<div class="media">
 						<a href="#" class="pull-left">
 							<img src="https://s3.amazonaws.com/uifaces/faces/twitter/fffabs/128.jpg" class="media-photo">
 						</a>
 						<div class="media-body">
 							<span class="media-meta pull-right">Febrero 13, 2016</span>
 							<h4 class="title">
 								Lorem Impsum
 								<span class="pull-right pendiente">(Pendiente)</span>
 							</h4>
 							<p class="summary">Ut enim ad minim veniam, quis nostrud exercitation...</p>
 						</div>
 					</div>
 				</td>
 			</tr>
 		</tbody>
 	</table>
 </div>

app/views/users/new.html.erb
<% if @user %>
  <h1>Signup!</h1>
<div class="sign-up-form">
  <%= form_for @user, :html => { :class => "form" } do |f| %>

  <!-- ERROR messages-->

    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@user.errors.count, "error") %> prohibited user from being saved:
        </h2>
        <ul>
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

  <!-- USER FORM-->
  <div class="control-group">
    <%= f.label :'first_name:', :class=>"control-label" %>
    <%= f.text_field :first_name, placeholder: "Homer", :class=>"form-control" %>
  </div>

  <div class="control-group">
    <%= f.label :'Username:', :class=>"control-label" %>
    <%= f.text_field :username, placeholder: "Donuts",:class=>"form-control" %>
  </div>

  <div class="control-group">
    <%= f.label :'email:', :class=>"control-label" %>
    <%= f.text_field :email, placeholder: "homer@gmail.com",:class=>"form-control" %>
  </div>

  <div class="control-group">
    <%= f.label :'password:', :class=>"control-label" %>
    <%= f.password_field :password, placeholder: "password", :class=>"form-control" %>
  </div>

  <div class="control-group">
    <%= f.label :'password confirmation:', :class=>"control-label" %>
    <%= f.password_field :password_confirmation, placeholder: "password", :class=>"form-control" %>
  </div>

  <div class="control-group">
    <%= f.label :'Profile Picture:', :class=>"control-label" %>
    <%= f.text_field :photo_url, :class=>"form-control" %>
  </div>

  <div class="control-group">
    <%= f.label :'Team Code:', :class=>"control-label" %>
    <%= f.text_field :team, placeholder: "01f1b7", :class=>"form-control" %>
  </div>

  <%= f.hidden_field(:account_manager, value: false) %>
  <br>
  <div class="submit-btn">
    <%= f.submit class:'btn btn-success' %>
  <% end %>

<% end %>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row profile">
		<div class="col-md-3">
			<div class="profile-sidebar">
				<!-- SIDEBAR USERPIC -->
				<div class="profile-userpic">
					<img src=<%= @user.profile_pic %> class="img-responsive" alt="">
				</div>
				<!-- END SIDEBAR USERPIC -->
				<!-- SIDEBAR USER TITLE -->
				<div class="profile-usertitle">
					<div class="profile-usertitle-name">
						<%= @user.username %>
					</div>
					<div class="profile-usertitle-job">
            <%= @user.email %>
					</div>
				</div>
				<!-- END SIDEBAR BUTTONS -->
				<!-- SIDEBAR MENU -->
				<div class="profile-usermenu">
					<ul class="nav">
						<li class="active">
							<a href="#">
							<i class="glyphicon glyphicon-home"></i>
							Overview </a>
						</li>
            <li class = "link">
              <%= link_to new_user_weight_path(@user) do%>
                <i class="glyphicon glyphicon-pencil"></i>
                New Weigh-in
              <% end %>
            </li>
            <li class = "link">
              <%= link_to users_path do%>
                <i class="glyphicon glyphicon-th-list"></i>
                View TEAM Summary
              <% end %>
            </li>
            <li class = "link">
              <%= link_to edit_user_path(@user) do%>
                <i class="glyphicon glyphicon-user"></i>
                Update Account
              <% end %>
            </li>
					</ul>
				</div>
				<!-- END MENU -->
			</div>
		</div>
		<div class="col-md-9">
      <% date = ["May-12", "May-19", "May-26",  "June-02", "June-09"] %>
      <div class="profile-content">
        <h2>Welcome <%= @user.first_name.capitalize %>!</h2>
        <br>
        <h3 class="table-header">Weign-in Summary</h3>
        <table class="table table-striped">
          <thead>
            <tr class = "header">
              <th></th>
              <% date.each do |date| %>
              <th>
                <%= date %>
              </th>
              <% end %>
            </tr>
          </thead>
          <tbody>
            <tr>
              <% count = 5 %>
              <td class="row_header"><strong>Weight</strong></td>
              <% @user.weights.each do |weight| %>
                <td><%= sprintf('%.2f', weight.weight) %>
                  <% count -= 1 %>
                  <% end %>
                </td>
              <% count.times do %>
                <td></td>
                <% end %>
            </tr>

            <tr>
              <td class="row_header"><strong>Weekly <br> Loss/Gain</strong></td>
                <td> - </td>
                <td> <%= @user.weights[1] ? number_to_percentage((((@user.weights[1].weight - @user.weights[0].weight)/@user.weights[0].weight) * 100), precision: 2) : ""  %></td>
                <td> <%= @user.weights[2] ? number_to_percentage((((@user.weights[2].weight - @user.weights[1].weight)/@user.weights[1].weight) * 100), precision: 2) : ""  %></td>
                <td> <%= @user.weights[3] ? number_to_percentage((((@user.weights[3].weight - @user.weights[2].weight)/@user.weights[2].weight) * 100), precision: 2) : ""  %></td>
                <td> <%= @user.weights[4] ? number_to_percentage((((@user.weights[4].weight - @user.weights[3].weight)/@user.weights[3].weight) * 100), precision: 2) : ""  %></td>
            </tr>

            <tr>
              <td class="row_header"><strong>Total <br> Loss/Gain</strong></td>
                <td> - </td>
                <td> <%= @user.weights[1] ? number_to_percentage((((@user.weights[1].weight - @user.weights[0].weight)/@user.weights[0].weight) * 100), precision: 2) : ""  %></td>
                <td> <%= @user.weights[2] ? number_to_percentage((((@user.weights[2].weight - @user.weights[0].weight)/@user.weights[0].weight) * 100), precision: 2) : ""  %></td>
                <td> <%= @user.weights[3] ? number_to_percentage((((@user.weights[3].weight - @user.weights[0].weight)/@user.weights[0].weight) * 100), precision: 2) : ""  %></td>
                <td> <%= @user.weights[4] ? number_to_percentage((((@user.weights[4].weight - @user.weights[0].weight)/@user.weights[0].weight) * 100), precision: 2) : ""  %></td>
            </tr>

          </tbody>
        </table>
      </div>

		</div>
	</div>
</div>

<br>
<br>

app/views/weights/new.html.erb
<!-- <h2>Create a New Product</h2> -->
<% date = ["May 12, 2016", "May 19, 2016", "May 26, 2016",  "June 02, 2016", "June 09, 2016"] %>
<fieldset>
	 <% if @user %>
		<legend> Input Weight</legend>
	<% else %>
		<legend> Edit Weight</legend>
	<% end %>

<%= form_for [@user, @weight], :html => { :class => "form-horizontal", :class => "form" }  do |f| %>
	<div class="control-group">
		<%= f.label :'Weight:', :class=>"control-label" %>
    <%= f.number_field :weight, :class=>"form-control", :class => 'text_field', :step => 'any' %>
	</div>

	<div class="control-group">
    <%= f.label :'Weigh-in Date:', :class=>"control-label" %>
    <%= f.select 'record_date', options_for_select(date) %>
	</div>
  <%= f.hidden_field(:user_id, :value => @user.id) %>

	<br>
	<div >
		<%= f.submit class: 'btn btn-success'%>
	</div>
<% end %>
</fieldset>